Av2 846/notification preference desktop
intersective/app pull request #1106
Opened 2021-02-21 23:14 UTC by ronakamani

**Story/Ticket Reference ID from JIRA:**
https://intersective.atlassian.net/browse/AV2-846

**Additional Comments:**
`Add here`

**Checklist:**

- [ x ] Unit test completed?: (Y/N)
- [ x ] Docs folder up to date?: (Y/N)
- [ x ] Add if anything missed: (Y/N)

All Checklist are okay.

This PR looks great - it's ready to merge! Please review and let's ship it. :)

2021-02-23 04:38 UTC, trtshen requested changes

2021-02-23 04:38 UTC, trtshen commented on src/app/preference/preference-modal/preference-modal.component.html
> +<ion-content color="light" class="pop-up-content test" text-center>
@ronakamani is the "test" necessary?

2021-02-23 04:38 UTC, trtshen commented on src/app/preference/preference-modal/preference-modal.component.html
> +    <ion-toolbar class="pn-title-toolbar">
@ronakamani i dont recommend to copy over the entire [preference.component.ts](https://github.com/intersective/app-v2/blob/AV2-846/Notification-preference-desktop/src/app/preference/preference.component.html) into a different file. it reduces code quality and maintainability.

how about try learn to use [Template syntax](https://angular.io/guide/architecture-components#template-syntax) to insert the instance of component view. 

In your case, 
eg. 
```html
<app-preference-component></app-preference-component>
```

2021-02-23 04:49 UTC, trtshen requested changes

2021-02-23 04:49 UTC, trtshen commented on src/app/preference/preference-modal/preference-modal.component.ts
> +  PreferenceUpdateModal(event, key) {
the naming convention should follow [camelCase](https://www.w3schools.com/js/js_conventions.asp#:~:text=camelCase%3A,with%20many%20JavaScript%20library%20names.)

2021-02-23 04:49 UTC, trtshen commented on src/app/preference/preference-modal/preference-modal.component.html
> +    <ion-header mode="ios">
it's should be the same for this  `#showUpdateModalTemplate` part.
this part using the entire same codebase as in [preference-update.component.html](https://github.com/intersective/app-v2/blob/AV2-846/Notification-preference-desktop/src/app/preference/preference-update/preference-update.component.html)

try practise [template syntax](https://angular.io/guide/architecture-components#template-syntax)

p/s: anything that's repeated, should be made as shareable "component". Next time, we dont need to edit multiple time/components for one similar change request.

2021-02-23 04:49 UTC, trtshen commented on src/app/shared/notification/notification.service.ts
> +  async PreferenceDesktopModal(message: string) {
naming convention follow [camelCase](https://www.w3schools.com/js/js_conventions.asp#:~:text=camelCase%3A,with%20many%20JavaScript%20library%20names.)

2021-03-17 03:29 UTC, closed without merging

2021-03-17 03:30 UTC, ronakamani commented
The UI had problem to be implemented. We decided to stop implementing in this way.