Av2 846 preference desktop new design
intersective/app pull request #1117
Opened 2021-03-04 10:48 UTC by ronakamani

**Story/Ticket Reference ID from JIRA:**
https://intersective.atlassian.net/browse/AV2-846

**Additional Comments:**
`Add here`

**Checklist:**

- [ x ] Unit test completed?: (Y/N)
- [ x ] Docs folder up to date?: (Y/N)
- [ x ] Add if anything missed: (Y/N)

All Checklist are okay.

This PR looks great - it's ready to merge! Please review and let's ship it. :)

2021-03-16 01:15 UTC, trtshen requested changes

2021-03-16 01:15 UTC, trtshen commented on src/app/preference/preference-update/preference-update.component.ts
> +  private getKey() {
@ronakamani can you please add docblock for this getkey() function?

2021-03-16 01:15 UTC, trtshen commented on src/app/preference/preference-update/preference-update.component.ts
> -   */
@ronakamani the docblock got deleted, can you please add back?

2021-03-16 01:15 UTC, trtshen commented on src/app/tabs/tabs-routing.module.ts
> +        path: 'preference',
@ronakamani do we need preference in tab?

2021-03-16 04:05 UTC, ronakamani commented on src/app/tabs/tabs-routing.module.ts
> +        path: 'preference',
@Chaw, yes we need that, if we delete this routing in the tab routing it won't show tabs toolbar on top of preference page.

2021-03-23 22:40 UTC, closed without merging

2021-03-23 22:40 UTC, ronakamani commented
the final branch is merged.