[AV2-915]
intersective/app pull request #1182
Opened 2021-05-26 09:45 UTC by shawnm0705

**Story/Ticket Reference ID from JIRA:**
`Add link here`

**Additional Comments:**
`Add here`

**Checklist:**

- [x] Unit test completed?: (Y/N)
- [x] Docs folder up to date?: (Y/N)
- [x] Add if anything missed: (Y/N)

All checklists are okay.

This PR looks great - it's ready to merge! Please review and let's ship it. :)

2021-05-26 09:51 UTC, trtshen approved these changes

2021-05-26 15:11 UTC, trtshen requested changes
test broken

2021-05-26 15:44 UTC, trtshen commented
@shawnm0705 not sure if cherry pick this would help 
https://github.com/intersective/app-v2/pull/1162/commits/45e145a7262d1781b27d43c8c9669c8c3490b11c

2021-05-27 02:36 UTC, sasangachathumal approved these changes

2021-05-27 04:27 UTC, trtshen approved these changes

2021-05-27 04:27 UTC, merged