[CORE-4930, CORE-4959] Full events changes need to do in App
intersective/app pull request #1309
Opened 2021-10-22 11:54 UTC by sasangachathumal

**Story/Ticket Reference ID from JIRA:**
https://intersective.atlassian.net/browse/CORE-4930
https://intersective.atlassian.net/browse/CORE-4959

**Additional Comments:**
### **Check Jura story videos to check how changes works in app.**

Update event book button to show fully booked if no capacity remaining
Added code to disabled fully booked if no capacity remaining.
updated unit test for new changes.
update code to reduce capacity by 1 when event got booked.
Add code to show fully booked in events list if no capacity remaining.

**Checklist:**

- [x] Unit test completed?: (Y/N)
- [x] Docs folder up to date?: (Y/N)
- [x] Add if anything missed: (Y/N)

All checklists are okay.

This PR looks great - it's ready to merge! Please review and let's ship it. :)

2021-10-23 01:06 UTC, shawnm0705 requested changes

2021-10-23 01:06 UTC, shawnm0705 commented on src/app/event-detail/event-detail.component.ts
> +        this.event.remainingCapacity -= 1;
why do we need to reduce the remainingCapacity here?

2021-10-25 01:38 UTC, sasangachathumal commented on src/app/event-detail/event-detail.component.ts
> +        this.event.remainingCapacity -= 1;
Main reason is, it' mention in the requirements of the story CORE-4930 and also in main story CORE-4853.
`When a booking is done by a user (learner or expert) on AppV2, AppV2’s max capacity shall reduce 1 unit`.

But I just check in stage environment it's reduce remaining capacity. So i think we can remove this code line. i will update this shawn.

2021-10-25 02:19 UTC, shawnm0705 commented on src/app/event-detail/event-detail.component.ts
> +        this.event.remainingCapacity -= 1;
That statement is what a user should see as the result. 
The reduction should happen in the API instead of the front-end.

2021-10-25 02:19 UTC, shawnm0705 approved these changes

2021-10-25 02:19 UTC, merged