Feature/av2 987/support multi day events
intersective/app pull request #1328
Opened 2021-11-29 10:30 UTC by sasangachathumal

**Story/Ticket Reference ID from JIRA:**
https://intersective.atlassian.net/browse/AV2-987

**Additional Comments:**
Check Jira story to see changes.

**Checklist:**

- [x] Unit test completed?: (Y/N)
- [x] Docs folder up to date?: (Y/N)
- [x] Add if anything missed: (Y/N)

All checklists are okay.

This PR looks great - it's ready to merge! Please review and let's ship it. :)

2021-12-01 15:42 UTC, trtshen submitted a review, later dismissed

2021-12-02 06:01 UTC, shawnm0705 requested changes
Please check my comments and fix the code smell

2021-12-02 06:01 UTC, shawnm0705 commented on src/app/event-list/event-list.service.ts
> +import * as moment from 'moment';
we'd better import 3rd party package in `utils.service` and create a function there, so that we can reuse it everywhere else

2021-12-06 04:15 UTC, shawnm0705 approved these changes

2021-12-08 00:49 UTC, merged