[AV2-1207] UX/UI Manual Save button and last save time in assessment UI
intersective/app pull request #1520
Opened 2022-07-12 02:53 UTC by sasangachathumal

**Story/Ticket Reference ID from JIRA:**
https://intersective.atlassian.net/browse/AV2-1207

**Additional Comments:**
Updated last save section hight and save button hight.
update last save section padding.
update last save to update through events (rxjs subjects).
update activity-desktop, assessment-mobile to broadcast that event.

**Checklist:**

- [x] Unit test completed?: (Y/N)
- [x] Docs folder up to date?: (Y/N)
- [x] Add if anything missed: (Y/N)

All checklists are okay.

This PR looks great - it's ready to merge! Please review and let's ship it. :)

2022-07-12 02:57 UTC, sasangachathumal commented
Please check jira story comments for video how it works now.

2022-07-12 03:18 UTC, shawnm0705 requested changes

2022-07-12 03:18 UTC, shawnm0705 commented on projects/v3/src/app/components/assessment/assessment.component.ts
> +  private _initSavingEvent() {
This `assessment.component` is a stand-alone component, which shouldn't subscribe to a global wide event.
Why do we need to check the saving message outside of this component?

2022-07-13 05:15 UTC, shawnm0705 requested changes

2022-07-13 05:15 UTC, shawnm0705 commented on projects/v3/src/app/components/assessment/assessment.component.ts
> +    if (!this.savingMessage || this.savingMessage === '') {
instead of this, we can simply put
```
if (this.savingMessage) {
return;
}
```

2022-07-13 05:15 UTC, shawnm0705 commented on projects/v3/src/app/pages/assessment-mobile/assessment-mobile.page.ts
> +      this.savingText = 'Last saved ' + this.utils.getFormatedCurrentTime();
the savingText is changed for both `if` and `else`, why don't we just bring it out of the `if,else` then?

2022-07-14 02:41 UTC, shawnm0705 requested changes

2022-07-14 02:41 UTC, shawnm0705 commented on projects/v3/src/app/pages/activity-desktop/activity-desktop.page.ts
> +    this.savingText = 'Last saved ' + this.utils.getFormatedCurrentTime();
the function will return `if (!event.assessment.inProgress)` so this should come before that

2022-07-14 03:31 UTC, shawnm0705 approved these changes

2022-07-14 03:31 UTC, merged